[Content]
ExtraTrees=
    ../../cosign.pub:/usr/share/pki/containers/barusu.pub

[Content]
RemoveFiles=
    /usr/lib/systemd/system/flatpak-add-fedora-repos.service
    /usr/share/applications/fcitx5-wayland-launcher.desktop
    /usr/share/applications/org.fcitx.Fcitx5*.desktop

VolatilePackages=
    systemd-container

Packages=
    bolt
    brightnessctl
    chezmoi
    just
    gum
    ddcutil
    default-fonts
    default-fonts-core-emoji
    distribution-gpg-keys
    fcitx5-chinese-addons
    fcitx5-mozc
    fcitx5-rime
    flatpak
    gcr
    generic-logos
    git-core
    glibc-all-langpacks
    gnome-keyring
    gnome-keyring-pam
    gnupg2-scdaemon
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    greetd
    greetd-selinux
    kf6-kimageformats
    librime-lua
    ncurses
    nmtui
    openrgb-udev-rules
    openssh-askpass
    orca
    pam-u2f
    playerctl
    qt6-qtimageformats
    qt6-qtmultimedia
    steam-devices
    udiskie
    webp-pixbuf-loader
    wl-clipboard
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-terminal-exec
    xdg-user-dirs
    xorg-x11-server-Xwayland
    #xwayland-satellite

# FIXME: Remove once https://github.com/systemd/mkosi/pull/4390 is merged
[Build]
ToolsTreePackages=
    passwd
