[Content]
VolatilePackages=
    # Explicit graphical infrastructure instead of the broad graphical package group.
    NetworkManager
    adwaita-icon-theme
    bluez
    dbus-broker
    firewalld
    fwupd
    gsettings-desktop-schemas
    mesa-dri-drivers
    mesa-libEGL
    mesa-libgbm
    mesa-libGL
    mesa-vulkan-drivers
    pipewire-alsa
    pipewire-pulseaudio
    plymouth
    plymouth-system-theme
    upower
    xdg-utils
    systemd-oomd-defaults

Packages=
    # Explicit graphical infrastructure instead of the broad graphical package group.
    NetworkManager
    adwaita-icon-theme
    bluez
    dbus-broker
    firewalld
    fwupd
    gsettings-desktop-schemas
    mesa-dri-drivers
    mesa-libEGL
    mesa-libgbm
    mesa-libGL
    mesa-vulkan-drivers
    pipewire-alsa
    pipewire-pulseaudio
    plymouth
    plymouth-system-theme
    upower
    xdg-utils
    alsa-firmware
    alsa-sof-firmware
    alsa-tools-firmware
    alsa-ucm
    alsa-utils
    atheros-firmware
    audispd-plugins
    brcmfmac-firmware
    cifs-utils
    cups
    cups-pk-helper
    dymo-cups-drivers
    fuse
    fuse-common
    gstreamer1-plugin-dav1d
    gstreamer1-plugin-openh264
    gvfs-gphoto2
    gvfs-mtp
    gvfs-nfs
    gvfs-smb
    hplip
    hyperv-daemons
    ifuse
    intel-audio-firmware
    iwlegacy-firmware
    iwlwifi-dvm-firmware
    iwlwifi-mvm-firmware
    jmtpfs
    kernel-modules-extra
    libcamera-gstreamer
    libcamera-v4l2
    libimobiledevice
    libratbag-ratbagd
    mesa-libGLU
    mobile-broadband-provider-info
    mt7xxx-firmware
    NetworkManager-adsl
    NetworkManager-bluetooth
    NetworkManager-config-connectivity-fedora
    NetworkManager-libnm
    NetworkManager-openconnect
    NetworkManager-openvpn
    NetworkManager-ssh
    NetworkManager-ssh-selinux
    NetworkManager-strongswan
    NetworkManager-vpnc
    NetworkManager-wifi
    NetworkManager-wwan
    nxpwireless-firmware
    openconnect
    open-vm-tools
    open-vm-tools-desktop
    pam_yubico
    pcsc-lite
    pipewire
    pipewire-gstreamer
    pipewire-utils
    printer-driver-brlaser
    ptouch-driver
    qemu-guest-agent
    realtek-firmware
    spice-vdagent
    steam-devices
    system-config-printer-libs
    system-config-printer-udev
    tiwilink-firmware
    tuned
    tuned-ppd
    udisks2-lvm2
    usb_modeswitch
    vpnc
    WALinuxAgent-udev
    wireguard-tools
    wireplumber
    xdg-user-dirs
